#!/usr/bin/env bash

# Branch-local release subset mirrored from the archived release runner.
# This enables the early performance pivots without forcing the later
# experimental pointer/patch/normalize branches that regressed the gate probe.

export ENABLE_REUSE_APPLY_OPT="${ENABLE_REUSE_APPLY_OPT:-1}"
export ENABLE_PRESERVED_SPLIT_OPT="${ENABLE_PRESERVED_SPLIT_OPT:-1}"
export ENABLE_WATCH_SCAN_OPT="${ENABLE_WATCH_SCAN_OPT:-1}"
export ENABLE_RETAIN_COMPACTION_OPT="${ENABLE_RETAIN_COMPACTION_OPT:-1}"
export ENABLE_KEPT_VECTOR_OPT="${ENABLE_KEPT_VECTOR_OPT:-1}"
export ENABLE_STABLE_COMPACTION_OPT="${ENABLE_STABLE_COMPACTION_OPT:-1}"
export ENABLE_BLOCK_COPY_COMPACTION_OPT="${ENABLE_BLOCK_COPY_COMPACTION_OPT:-1}"
export ENABLE_COPY_PLAN_BUILD_OPT="${ENABLE_COPY_PLAN_BUILD_OPT:-1}"
export ENABLE_RUN_DISCOVERY_FUSION_OPT="${ENABLE_RUN_DISCOVERY_FUSION_OPT:-1}"
export ENABLE_FUSED_DISCOVERY_CLASSIFY_OPT="${ENABLE_FUSED_DISCOVERY_CLASSIFY_OPT:-1}"
export ENABLE_TSCAN_CORE_OPT="${ENABLE_TSCAN_CORE_OPT:-1}"
export ENABLE_TSCAN_BRANCH_STATE_OPT="${ENABLE_TSCAN_BRANCH_STATE_OPT:-1}"
export ENABLE_STATE_LOAD_MATERIALIZATION_OPT="${ENABLE_STATE_LOAD_MATERIALIZATION_OPT:-1}"
export ENABLE_PREV_STATE_CARRY_REUSE_OPT="${ENABLE_PREV_STATE_CARRY_REUSE_OPT:-1}"
export ENABLE_CARRY_REUSE_FASTPATH_OPT="${ENABLE_CARRY_REUSE_FASTPATH_OPT:-1}"
export ENABLE_CARRY_HIT_APPLY_OPT="${ENABLE_CARRY_HIT_APPLY_OPT:-1}"
