#!/usr/bin/env bash
set -euo pipefail
# Remaining progress38 authoritative rows
# 1) close carried progress35 release rows if still needed
# 2) run dense 1024 release
# 3) run dense 1024 repeat
# 4) run dense 4096 representative
# 5) run multi 4096 representative

COMMON_ENVS=(
  ENABLE_REUSE_APPLY_OPT=1
  ENABLE_PRESERVED_SPLIT_OPT=1
  ENABLE_WATCH_SCAN_OPT=1
  ENABLE_RETAIN_COMPACTION_OPT=1
  ENABLE_KEPT_VECTOR_OPT=1
  ENABLE_STABLE_COMPACTION_OPT=1
  ENABLE_BLOCK_COPY_COMPACTION_OPT=1
  ENABLE_COPY_PLAN_BUILD_OPT=1
  ENABLE_RUN_DISCOVERY_FUSION_OPT=1
  ENABLE_FUSED_DISCOVERY_CLASSIFY_OPT=1
  ENABLE_TSCAN_CORE_OPT=1
  ENABLE_TSCAN_BRANCH_STATE_OPT=1
  ENABLE_STATE_LOAD_MATERIALIZATION_OPT=1
  ENABLE_PREV_STATE_CARRY_REUSE_OPT=1
  ENABLE_CARRY_REUSE_FASTPATH_OPT=1
  ENABLE_CARRY_HIT_APPLY_OPT=1
  ENABLE_PREV_STATE_WRITEBACK_OPT=1
  ENABLE_TARGET_RESOLVE_PINNING_OPT=1
  ENABLE_POINTER_REBIND_OPT=1
  ENABLE_DIRECT_PREBIND_OPT=1
  ENABLE_REBIND_COMMIT_OPT=1
  ENABLE_METADATA_PATCH_SLOT_OWNER_OPT=1
  ENABLE_SLOT_OWNER_UPDATE_OPT=1
  ENABLE_SLOT_OWNER_PATCH_COMMIT_OPT=1
  ENABLE_SLOT_OWNER_FIELD_PATCH_OPT=1
  ENABLE_COMPACT_FIELD_PACK_OPT=1
  ENABLE_PACK_ENCODE_NORMALIZE_OPT=1
)

echo 'Use run_progress38_case_supervised.py one case at a time for:'
printf '  %s
' \
  both_on_dense_1024_release \
  both_on_dense_1024_release_repeat \
  both_on_dense_4096_release \
  both_on_multi_4096_release
